defaults:
  - base_config
  - _self_

  - override hydra/launcher: submitit_local
  # - override hydra/launcher: submitit_slurm

env_exp_id: 0
overwrite: false
n_proc: 8
batch_size: 40
game: maze_for_evo_2
mutate_rules: true
evaluate: false
save_freq: 1
eval_freq: 5
render: false
workspace: ../gen-game-runs
runs_dir_evo: evo_env
runs_dir_rl: rl_player
runs_dir_il: il_player

load_gen: null
# aggregate_playtraces: false

hydra:
  # sweeper:
  #   params:
  #     env_exp_id: 0, 1, 2
  

  launcher:
    tasks_per_node: 1
    cpus_per_task: 40
    gpus_per_node: 0
    timeout_min: 2880
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False
