defaults:
  - base_config
  - _self_

  # - override hydra/launcher: basic
  # - override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm


hydra:
  launcher:
    tasks_per_node: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 2880
    mem_gb: 30

  sweeper:
    params:
      # env_exp_id: 14, 15, 16
      env_exp_id: 14
      # evo_seed: 0
      evo_seed: 0, 1, 2, 3, 4, 5
      # evo_seed: 3, 4, 5
  

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False
