defaults:
  - il_config
  - _self_

  # - override hydra/launcher: basic
  - override hydra/launcher: submitit_slurm

hydra:
  sweeper:
    params:
      # load_gen: 5, 10, 15, 20
      load_gen: 15
  
  launcher:
    tasks_per_node: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 2880
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False

env_exp_id: 14

load_il: True
save_freq: 10_000
eval_freq: 10_000
# n_il_batches: 100000
overwrite: false
record: false
game: blank_for_evo
# n_epochs: null
n_il_batches: 500_000
