defaults:
  - evo
  - _self_

load_il: True
save_freq: 10_000
eval_freq: 10_000
# n_il_batches: 100000
env_exp_id: 0
overwrite: false
record: false
game: blank_for_evo
# n_epochs: null
n_il_batches: 500_000

hydra:
  job:
    chdir: false