defaults:
  - train_accel_xlife
  - _self_

# - override hydra/launcher: basic
# - override hydra/launcher: submitit_local
  # - override hydra/launcher: submitit_slurm

hydra:
  verbose: false
  sweeper:
    params:
      # lr: 1e-3, 1e-4, 1e-5, 1e-6

  # launcher:
  #   tasks_per_node: 1
  #   cpus_per_task: 1
  #   gpus_per_node: 1
  #   timeout_min: 1440
  #   mem_gb: 30
