defaults:
  # - override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm

exp_id: 0
overwrite: false
num_proc: 40
batch_size: 40
game: maze_for_evo
mutate_rules: true
evaluate: false
save_freq: 1
render: false
record: false
workspace: ../gen-game-runs
runs_dir: runs_evo
log_dir: null  # Set later, automatically
load_gen: null
aggregate_playtraces: false

hydra:
  sweeper:
    params:
      exp_id: 0, 1, 2
  

  launcher:
    tasks_per_node: 1
    cpus_per_task: 40
    gpus_per_node: 0
    timeout_min: 2880
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False
