defaults:
  # - base_config
  - _self_  # So we can append with `+experiment`

  - override hydra/launcher: submitit_slurm 
  # - override hydra/launcher: submitit_local

hydra:
  sweeper:
    params:
      env: maze, dungeon, hamilton, maze_backtracker, maze_growth, maze_npc, maze_spike, power_line, sokoban
      lr: 1e-3

  launcher:
    tasks_per_node: 1
    cpus_per_task: 10
    gpus_per_node: 1
    timeout_min: 300
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False


env: maze
lr: 1e-3
resume: true
render: false

num_workers: 10
num_gpus: 1

infer: false
record: false

debug: false